version: 2
name: 未命名项目
description: ""
global:
  concurrent: 1
trigger:
  webhook: gitlink@1.0.0
  event:
    - ref: pr
      ruleset-operator: AND
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: git_clone_0
    name: git clone
    task: git_clone@1.2.9
    input:
      username: ((dmz.use_name))
      password: ((dmz.user_code))
      remote_url: '"https://gitlink.org.cn/yuyebo22/reposync.git"'
      ref: '"refs/heads/master"'
      commit_id: '""'
      depth: 1
    needs:
      - start
  - ref: docker_image_build_0
    name: docker镜像构建
    task: docker_image_build@1.6.0
    input:
      docker_username: ((dmz.aliyun_name))
      docker_password: ((dmz.aliyun_key))
      image_name: '"registry.cn-hangzhou.aliyuncs.com/dmzchangsha/yunwei"'
      image_tag: '"latest"'
      registry_address: '"registry.cn-hangzhou.aliyuncs.com"'
      docker_file: '"Dockerfile"'
      docker_build_path: '"."'
      workspace: git_clone_0.git_path
      image_push: true
      build_args: '""'
    needs:
      - git_clone_0
  - ref: ssh_cmd_0
    name: ssh执行命令
    task: ssh_cmd@1.1.1
    input:
      ssh_pass: ((dmz.ssh_key))
      ssh_ip: '"47.98.110.189"'
      ssh_port: '"22"'
      ssh_user: '"root"'
      ssh_cmd: "\"docker stop yunwei || true && docker rm yunwei || true && docker
        pull registry.cn-hangzhou.aliyuncs.com/dmzchangsha/yunwei:latest; docker
        run -d -p 8089:8000 --name yunwei -e BOOT_MODE='app'
        registry.cn-hangzhou.aliyuncs.com/dmzchangsha/yunwei:latest\""
    needs:
      - docker_image_build_0
  - ref: end
    name: 结束
    task: end
    needs:
      - ssh_cmd_0

